###
GET http://localhost:8080/customers
Accept: application/json

###
GET http://localhost:8080/customers/1
Accept: application/json

###
POST http://localhost:8080/customers
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "phoneNumber": "123-456-7890",
    "cpf": "12345678900"
}
